### ISSUE TITLE
Add an url to a readme (markdown) to the package

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/main#41]
It would be nice to add an url to a readme (markdown) to the package:

```yaml
name: Dummy App
type: desktop-application # not sure we need that
categories:
- Media
custom:
- repo: https://github.com//johndoe/harbour-dummy-app/
icon: https://raw.githubusercontent.com//johndoe/harbour-dummy-app/master/harbour-dummy-app.svg
screenshots:
- https://github.com/johndoe/harbour-dummy-app/raw/master/metadata/screenshots/screenshot1.png
- https://github.com//johndoe/harbour-dummy-app/raw/master/metadata/screenshots/screenshot2.png
- https://github.com//johndoe/harbour-dummy-app/raw/master/metadata/screenshots/screenshot3.png
url:
- donation: https://www.paypal.me/johndoe
- readme: https://github.com/johndoe/harbour-dummy-app/raw/master/README.md
```
This could be rendered in Chum GUI instead of the description if present.

_Originally posted by @black-sheep-dev in https://github.com/sailfishos-chum/main/issues/29#issuecomment-1008158448_
